### PR TITLE
Allowing deepmerge of dictionaries

### PR DESCRIPTION
**Pull request by diequeiroz**
## Proposed Changes
  - Allowing deepmerge of dictionaries.

When I have the following yaml structure:
```yaml
parent:
   child1: value1
   child2: value2
   child3: value3
```
Then I have a environment variable that overrides child3:
```shell 
parent__child3=value4 python myscript.py
```
This result in the following config:
```python
{'parent': {'value3': 'override3'}}
```
This PR fixes this.

### CODE REVIEW

**Comment by andrasmaroy** [comment]
Nice, I've ran into this in the past but forgot how to reproduce :) Thanks for fixing it!

Please add a unit test that covers this error and I'd rather bump a fix version (1.5.1 instead of 1.6.0) for this, otherwise looks good.

**Comment by diequeiroz** [comment]
@andrasmaroy what about now?

I was having trouble with the globals `TEST_FILE_RESULT` and `TEST_ENV_RESULT`. Something was modifying their value along the two test cases. I didn't figure out what, so I moved them to the test setup.

Since `TestHierarchy` was already testing overlap, I just added the deep merge case to it. If you think the deep merge tests belong somewhere else, please let me know.

**Comment by diequeiroz** [comment]
Thanks for accepting these changes. When are you planning to release the 1.5.1?

**Comment by andrasmaroy** [comment]
Just released 1.6.0 including these changes as well. ;)

**Pull request merged**
